# Site settings
title: Millennium Glass
email: accounts@millenniumglass.com.au
description: Gold Coast Supplier and installer of Showerscreens, Mirrors, Splashbacks, Wardrobe Doors, Shelving, Pool fencing and Glass Balustrade.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://millenniumglass.com.au/"
permalink: /:categories/:title/
permalink: /:year/:month/:day/:title/
breadcrumbs: true  # disabled by default
include: ['_pages']
collections:
  accessories:
      output: true
      permalink: /products/:categories/:path/
  aluminium-fencing:
      output: true
      permalink: /products/:categories/:path/
  glass-fencing:
      output: true
      permalink: /products/:categories/:path/
  wardrobe-doors:
      output: true
      permalink: /products/:categories/:path/
  mirrors:
      output: true
      permalink: /products/:categories/:path/
  showerscreens:
      output: true
      permalink: /products/:categories/:path/
  splashbacks:
      output: true
      permalink: /products/:categories/:path/

# Build settings
markdown: kramdown

source:      .
exclude:
  - special.css
  - style.css
destination: ./_site
plugins_dir:     ./_plugins

css_source_dir:  css
css_output_file: /css/style.min.css

exclude:
  - package.json
  - node_modules
  - gulpfile.js
  - s3_website.yml
  - Gemfile
  - Rakefile
  - deploy.sh

# Server Config options
livereload: true     # You no longer need to include --livereload
reload_port: 5678    # If you don't want to use the default port

plugins: [jekyll-paginate]
paginate: 4
paginate_path: /blog/page:num/

username: developer@millenniumglass.com.au
server_url: ftp.millenniumglass.com.au
remote_dir: /public_html
