---
label: Product Page
hide_body: false
fields:
- type: text
  name: layout
  label: layout
  default: products
  config:
    required: true
  hidden: true
- type: text
  name: title
  label: title
- type: text
  name: description
  label: description
- name: image_path
  type: file
  config:
    maxSize: 64
  label: image_path
  description: Feature image
- name: category
  type: select
  default: ''
  config:
    required: false
    options:
    - showerscreens
    - mirrors
    source:
      type: simple
      section: 
      file: 
      path: 
  label: category
- name: product
  type: select
  default: []
  config:
    required: false
    options:
    - frameless-showerscreens
    - framed-showerscreens
    - panel-showerscreens
    - semi-frameless-showerscreens
    source:
      type: simple
      section: 
      file: 
      path: 
  label: product
- type: textarea
  name: value-prop
  label: value-prop
- type: text
  name: buybutton
  label: buybutton
- name: gallery
  type: image_gallery
  config: {}
  label: gallery
