---
label: Product Page
hide_body: false
fields:
- type: text
  name: layout
  label: layout
  default: products
  config:
    required: true
  hidden: true
- type: text
  name: title
  label: title
- type: text
  name: description
  label: description
- name: hero_image
  type: file
  config:
    maxSize: 64
  label: Hero Image
  description: The main image feature image
- name: category
  type: select
  default: ''
  config:
    required: false
    options:
    - showerscreens
    - mirrors
    source:
      type: simple
      section: 
      file: 
      path: 
  label: category
- name: product
  type: select
  default: []
  config:
    required: false
    options:
    - frameless-showerscreens
    - framed-showerscreens
    - panel-showerscreens
    - semi-frameless-showerscreens
    source:
      type: simple
      section: 
      file: 
      path: 
  label: product
- type: textarea
  name: value-prop
  label: value-prop
- name: do_you_need_a_buy_button
  type: boolean
  label: Do you need a buy button
  description: Click to add a buy button in the hero image
  default: false
- type: text
  name: buybutton
  label: buybutton
  showOnly:
    field: do_you_need_a_buy_button
    value: true
  description: Enter the URL of the online store
- name: images
  type: image_gallery
  config: {}
  label: Image Gallery
pages:
- _showerscreens/tits.md
