---
label: Product Page
hide_body: false
fields:
- type: text
  name: layout
  label: layout
  default: products
  config:
    required: false
  hidden: true
- type: text
  name: title
  label: title
- type: text
  name: description
  label: description
- name: hero_image
  type: file
  config:
    maxSize: 64
  label: Hero Image
  description: The main image feature image
- name: category
  type: select
  default: ''
  config:
    required: false
    options:
    - showerscreens
    - mirrors
    - glass-fencing
    - wardrobe-doors
    source:
      type: simple
      section: 
      file: 
      path: 
  label: category
- name: product
  type: select
  default: []
  config:
    required: false
    options:
    - frameless-showerscreens
    - framed-showerscreens
    - panel-showerscreens
    - semi-frameless-showerscreens
    - beveled-mirrors
    - framed-mirrors
    - frameless-mirrors
    - micro-edge-mirrors
    - oval-mirrors
    - Frameless Glass Pool Fencing
    - glass-balustrading
    - Semi-Frameless Glass Pool Fencing
    - colour-back
    - mirrorline
    - premium-vinyl-colour
    - slimline
    - shoji
    - vinyl-colour
    - woodgrain
    source:
      type: simple
      section: 
      file: 
      path: 
  label: product
- name: 2-col-left
  type: include
  config: {}
  template: 2-col-image-left
  label: 2-col-left
- name: do_you_need_a_buy_button
  type: boolean
  label: Do you need a buy button
  description: Click to add a buy button in the hero image
  default: false
- type: text
  name: buybutton
  label: buybutton
  showOnly:
    field: do_you_need_a_buy_button
    value: true
  description: Enter the URL of the online store
- name: images
  type: image_gallery
  config: {}
  label: Images
- name: intro
  type: text
  config:
    required: false
  label: Introduction
  description: Introduction text
- name: include_brochure
  type: boolean
  label: Brochure
  description: Include a brochure on the page
- name: brochure
  type: file
  config:
    maxSize: 64
  label: Brochure
  description: Upload PDF of brochure
  showOnly:
    field: include_brochure
    value: true
pages:
- _glass-fencing/frameless.html
- _glass-fencing/glass-balustrading.html
- _glass-fencing/glass-stair-balustrading.html
- _glass-fencing/semi-frameless.html
- _mirrors/beveled.html
- _mirrors/framed.html
- _mirrors/frameless.html
- _mirrors/micro-edge.html
- _mirrors/oval.html
- _showerscreens/framed.md
- _showerscreens/frameless.html
- _showerscreens/panel.html
- _showerscreens/semi-frameless.html
- _wardrobe-doors/colour-back.html
- _wardrobe-doors/mirror.html
- _wardrobe-doors/mirrorline.html
- _wardrobe-doors/premium-vinyl-colour.html
- _wardrobe-doors/shoji.html
- _wardrobe-doors/slimline.html
- _wardrobe-doors/softline.html
- _wardrobe-doors/vinyl-colour.html
- _wardrobe-doors/woodgrain.html
